BeeBack.Web/BeeBack.Web/Controllers/ActivitiesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using BeeBack.Web.Interfaces;
using BeeBack.Web.ViewModels.Activities;
using Microsoft.AspNet.Identity;

namespace BeeBack.Web.Controllers
{
    [Authorize]
    public class ActivitiesController : Controller
    {
        private readonly IActivityService _activityService;
        private readonly IUserService _userService;

        public ActivitiesController(IActivityService activityService, IUserService userService)
        {
            _activityService = activityService;
            _userService = userService;
        }

        [AllowAnonymous]
        // GET: Activities
        public async Task<ActionResult> Index()
        {
            var activities = await _activityService.GetActivities(includeUserActivities: true);

            var viewModel = new ActivitiesIndexViewModel
            {
                Activities = activities.Select(model => model.ToViewModel<ActivityListItemViewModel>(User.Identity.GetUserId()))
            };

            return View(viewModel);
        }

        // GET: Activities/Details/5
        public async Task<ActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var activity = await _activityService.GetActivity(id.Value, true);

            if (activity == null)
            {
                return HttpNotFound();
            }

            var viewModel = activity.ToViewModel<ActivityDetailViewModel>(User.Identity.GetUserId());
            viewModel.Fill(activity);

            var subscribers = await _activityService.GetActivitySubscribers(id.Value);
            subscribers = subscribers.Where(s => s.Id != activity.UserId && s.Id != activity.DriverId).ToList();
            viewModel.Subscribers = subscribers;

            viewModel.User = _userService.GetUserById(activity.UserId);
            viewModel.Driver = _userService.GetUserById(activity.DriverId);

            return View(viewModel);
        }

        // GET: Activities/Create
        public ActionResult Create()
        {
            var viewModel = new ActivityCreateEditViewModel();

            return View("CreateEdit", viewModel);
        }

        // POST: Activities/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ActivityCreateEditViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                viewModel.Id = Guid.NewGuid();

                var model = viewModel.ToModel();
                model.UserId = User.Identity.GetUserId();

                await _activityService.AddActivity(model);

                return RedirectToAction("Index");
            }

            return View("CreateEdit", viewModel);
        }

        // GET: Activities/Edit/5
        public async Task<ActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var activity = await _activityService.GetActivity(id.Value);

            if (activity == null)
            {
                return HttpNotFound();
            }

            var viewModel = activity.ToViewModel<ActivityCreateEditViewModel>();

            return View("CreateEdit", viewModel);
        }

        // POST: Activities/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(ActivityCreateEditViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var activity = await _activityService.GetActivity(viewModel.Id);
                activity.Title = viewModel.Title;
                activity.Description = viewModel.Description;
                activity.ShortCode = viewModel.ShortCode;

                await _activityService.EditActivity(activity);

                return RedirectToAction("Index");
            }
            return View("CreateEdit", viewModel);
        }

        // GET: Activities/Delete/5
        public async Task<ActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var activity = await _activityService.GetActivity(id.Value);

            if (activity == null)
            {
                return HttpNotFound();
            }

            var viewModel = activity.ToViewModel<ActivityViewModel>();

            return View(viewModel);
        }

        // POST: Activities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(Guid id)
        {
            var activity = await _activityService.GetActivity(id);

            await _activityService.DeleteActivity(activity);

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _activityService.Dispose();
            }

            base.Dispose(disposing);
        }
    }
}

BeeBack.Web/BeeBack.Web/Views/Shared/_Layout.cshtml
@using BeeBack.Web.Models
@using Microsoft.AspNet.Identity
<!-- BeeBack Theme - Andrea Galanti /-->
<!doctype html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if IE 9]>    <html class="no-js ie9" lang="en"> <![endif]-->
<!--[if gt IE 9]><!-->
<html>
<!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">
    <meta name="description" content="BeeBack Free Flat and Responsive HTML5 Template ">
    <meta name="author" content="">

    <title>BeeBack</title>

    <!-- Bootstrap core CSS -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom Google Web Font -->
    <link href="~/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Arvo:400,700' rel='stylesheet' type='text/css'>

    <!-- Custom CSS-->
    <link href="~/css/general.css" rel="stylesheet">

    <!-- Owl-Carousel -->
    <link href="~/css/custom.css" rel="stylesheet">
    <link href="~/css/owl.carousel.css" rel="stylesheet">
    <link href="~/css/owl.theme.css" rel="stylesheet">
    <link href="~/css/style.css" rel="stylesheet">
    <link href="~/css/animate.css" rel="stylesheet">
    <link href="~/css/toastr.css" rel="stylesheet" />

    <!-- Magnific Popup core CSS file -->
    <link rel="stylesheet" href="~/css/magnific-popup.css">

    <!-- Modernizr -->
    @Scripts.Render("~/bundles/modernizr")

    <!--[if IE 9]>
        <script src="~/js/PIE_IE9.js"></script>
    <![endif]-->
    <!--[if lt IE 9]>
        <script src="~/js/PIE_IE678.js"></script>
    <![endif]-->
    <!--[if lt IE 9]>
        <script src="~/js/html5shiv.js"></script>
    <![endif]-->

    <link rel="stylesheet" href="~/css/beeback.css"/>

</head>

<body id="home" data-action="@Request.RequestContext.RouteData.Values["action"].ToString().ToLower()"
      data-controller="@Request.RequestContext.RouteData.Values["controller"].ToString().ToLower()">

    <!-- Preloader -->
    <div id="preloader">
        <div id="status"></div>
    </div>

    @RenderSection("preheader", required: false)


    <!-- NavBar-->
    <nav class="navbar-default" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index", "Home")">BeeBack</a>
            </div>

            <div class="collapse navbar-collapse navbar-right navbar-ex1-collapse">
                @RenderSection("navbar", false)
                <ul class="nav navbar-nav">
                    <li class="menuItem">
                        <a href="@Url.Action("Index", "Activities")">Activités</a>
                    </li>

                    @if (Request.IsAuthenticated)
                    {
                        <li class="menuItem">
                            @Html.ActionLink(User.Identity.GetUserName(), "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })
                        </li>
                            @*<li class="menuItem">
                                    @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                                    {
                                        <span>@Html.AntiForgeryToken()</span>


                                        <a href="javascript:document.getElementById('logoutForm').submit()">Log off</a>
                                    }
                                </li>*@
                    }
                    else
                    {
                        <li class="menuItem"><a href="#" data-toggle="modal" data-target="#login-modal">Login</a></li>
                    }
                </ul>
            </div>

        </div>
    </nav>

    @if (ViewBag.Landing == null || !ViewBag.Landing)
    {
        @:<div class="content-section-b" style="border-top: 0; padding: 0 0 24px 0">
        @:<div class="container">
    }

    @RenderBody()

    @if (ViewBag.Landing == null || !ViewBag.Landing)
    {
        @:</div>
        @:</div>
    }

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-7">
                    <h3 class="footer-title"></h3>

                    <!-- LICENSE -->
                    <a rel="cc:attributionURL" href="http://www.andreagalanti.it/lab/flatfy/"
                       property="dc:title">Flatfy Theme</a> by
                    <a rel="dc:creator" href="http://www.andreagalanti.it"
                       property="cc:attributionName">Andrea Galanti</a>
                    is licensed to the public under
                    <BR>the <a rel="license"
                               href="http://creativecommons.org/licenses/by-nc/3.0/it/deed.it">
                        Creative
                        Commons Attribution 3.0 Lice-nse - NOT COMMERCIAL
                    </a>.


                </div> <!-- /col-xs-7 -->

                <div class="col-md-5">
                    <div class="footer-banner">
                        <h3 class="footer-title">Navigation</h3>
                        <ul>
                            <li>Accueil</li>
                            <li>Activités</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <!-- JavaScript -->

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/toastr")
    @Scripts.Render("~/bundles/app")

    <script src="~/js/owl.carousel.js"></script>
    <script src="~/js/script.js"></script>
    <!-- StikyMenu -->
    <script src="~/js/stickUp.min.js"></script>
    <script type="text/javascript">
        jQuery(function ($) {
            $(document).ready(function () {
                $('.navbar-default').stickUp();

            });
        });

    </script>
    <!-- Smoothscroll -->
    <script type="text/javascript" src="~/js/jquery.corner.js"></script>
    <script src="~/js/wow.min.js"></script>
    <script>
        new WOW().init();
    </script>
    <script src="~/js/classie.js"></script>
    <script src="~/js/uiMorphingButton_inflow.js"></script>
    <!-- Magnific Popup core JS file -->
    <script src="~/js/jquery.magnific-popup.js"></script>


    @RenderSection("scripts", required: false)

    <!-- Login Modal -->
    <div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="login-modal-label">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="login-modal-label">Login</h4>
                </div>
                <div class="modal-body">
                    @Html.Partial("_LoginFormPartial", new LoginViewModel())
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Login</button>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

BeeBack.Web/BeeBack.Web/Views/Shared/_LoginFormPartial.cshtml
@model BeeBack.Web.Models.LoginViewModel

<section id="loginForm">
    @using (Html.BeginForm("Login", "Account", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
        @Html.AntiForgeryToken()
        <h4>Use a local account to log in.</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
                </div>
            </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <div class="checkbox">
                            @Html.CheckBoxFor(m => m.RememberMe)
                            @Html.LabelFor(m => m.RememberMe)
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Log in" class="btn btn-default" />
                    </div>
                </div>
                <p>
                    @Html.ActionLink("Register as a new user", "Register", "Account")
                </p>
                @* Enable this once you have account confirmation enabled for password reset functionality
                    <p>
                        @Html.ActionLink("Forgot your password?", "ForgotPassword")
                    </p>*@
    }
</section>